### ISSUE TITLE
Allow to specify multiple `appID`s depending on role

### ISSUE THREAD

**Issue by harnyk** [in4it/onelogin-auth-cli#8]
## Problem

Currently, one account can only be associated with one `appID`. This seems to be an issue, because some configurations a specific `appID` per each role.

## Solution

Allow to optionally specify multiple `appID`s depending on role using a map field `appIDsByRole` in the `account` struct.

Example:

```yaml
accounts:
  - name: ACME Dev
    appIDsByRole:
      admin: "123456"
      readonly: "987654"
    accountID: "111111111111"
    profileName: acme-dev

roles:
  - admin
  - readonly

```

## Backwards compatibility

This is backwards compatible, because if `appIDsByRole` is not specified, the `appID` field is used.
